services:
  localstack:
    image: localstack/localstack:latest
    container_name: event-driven-localstack
    ports:
      - "4567:4566"
    environment:
      - SERVICES=s3,sqs,lambda,cloudwatch
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack:/etc/localstack/init/ready.d"
